config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  resources :projects do
    resources :add_project_member, only: %w[new create destroy]
    resources :missions, only: %w[show new create edit update destroy] do
      resources :tasks, only: %w[show new create edit update destroy]
      resources :topics, only: %w[show new create edit update destroy] do
        resources :messages
      end
    end
  end
  resources :users, only: %w[show update destroy]

end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :mission
  has_many :messages, dependent: :destroy
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :is_member?
  before_action :is_manager?, only: [:new, :create, :edit, :update, :destroy]

  def new
    @topic = Topic.new
    @project = Project.find_by(id: params[:project_id])
    @mission = Mission.find_by(id: params[:mission_id])
  end

  def create
    topic = Topic.new(topic_params)
    topic.mission = Mission.find(params[:mission_id])
    topic.save

    redirect_to project_mission_path(topic.mission.project, topic.mission)
  end

  def show
    @topic = Topic.find_by(id: params[:id])
    @message = Message.new
  end

  def edit
    @topic = Topic.find_by(id: params[:id])
  end

  def update
    topic = Topic.find_by(id: params[:id])
    topic.title = topic_params[:title]
    if topic_params[:status] == 'Close'
      topic.status = 1
    elsif topic_params[:status] == 'Open'
      topic.status = 2
    end
    topic.save

    redirect_to project_mission_topic_path(topic.mission.project, topic.mission)

  end

  def destroy
    topic = Topic.find_by(id: params[:id])
    project = topic.mission.project
    mission = topic.mission
    topic.destroy

    redirect_to project_mission_path(project, mission)
  end

    private

  def topic_params
    params.require(:topic).permit(:title, :status)
  end

  def is_member?
    if Project.find_by(id: params[:project_id]) != nil && Project.find_by(id: params[:project_id]).users.include?(current_user)
    else
      redirect_to root_path
    end
  end

  def is_manager?
    if Project.find_by(id: params[:project_id]) != nil && Project.find_by(id: params[:project_id]).manager == current_user
    else
      redirect_to root_path
    end
  end
end

app/views/topics/edit.html.erb
<br>
<div class="container">
  <div class="form">
    <%= simple_form_for @topic, url: project_mission_topic_path(@topic.mission.project, @topic.mission, @topic), method: :patch do |f| %>
    <h2 class="far fa-edit"> Update your topic</h2>
    <%= f.input :title, label: "Title:" %>
    <%= f.input :status, label: 'Status', collection: ['Open', 'Close'], required: true %>
    <%= f.button :submit, value: 'Update', "data-disable-with" => "Creating..", class: "btn btn-outline-primary" %>
  <% end %>
  </div>

  <br>
</div>

app/views/topics/new.html.erb
<br>
<div class="container">
  <div class="form">
    <%= simple_form_for @topic, url: project_mission_topics_path(@project, @mission), method: :post do |f| %>
    <h2 class="far fa-comments">+ Open a topic:</h2>
    <%= f.input :title, label: "Title:" %>
    <%= f.button :submit, value: 'New topic', "data-disable-with" => "Creating..", class: "btn btn-outline-primary" %>
  <% end %>
  </div>
  <br>
</div>

app/views/topics/show.html.erb
<br>
<div class="container">
  <div class="card text-center">
    <div class="card-header">
      <ul class="nav nav-pills card-header-pills"><i class=""></i>
        <% if current_user == @topic.mission.project.manager%>
          <li class="nav-item">
            <%= link_to "", edit_project_mission_topic_path(@topic.mission.project, @topic.mission, @topic), method: :get, class: 'nav-link far fa-edit bigger-icon' %>
            <div class="hint">Edit topic</i></div>
          </li>
          <li class="nav-item">
             <%= link_to "", project_mission_topic_path(@topic.mission.project, @topic.mission, @topic), method: :delete, data: { confirm: 'Are you sure?', disable_with: 'loading...' }, class: 'nav-link far fa-trash-alt bigger-icon' %>
             <div class="hint red">Delete topic</i></div>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="card-body">
      <br>
      <h2 class="card-title far fa-comments"> <%= @topic.title %></h2>
      <br><hr><br>
      <% if @topic.status == 2 || @topic.status == nil %>
        <h2 class="card-title far fa-comment"> New message </h2>
        <%= simple_form_for @message, url: project_mission_topic_messages_path(@topic.mission.project, @topic.mission, @topic), method: :post do |f| %>
            <%= f.input :content  ,label: "Collaborate and make it happend!"  %>
          <%= f.button :submit, value: 'Publish', "data-disable-with" => "Creating..", class: "btn btn-outline-primary" %>
        <% end %>
      <% else %>
          <h3>Closed</h3>
      <% end %>
    </div>
  </div>
  <br><br>
  <div class="card-body" id="messages" data-topic-id="<%= @topic.id %>">
    <% @topic.messages.order(created_at: :desc).each do |message| %>
      <%= render "messages/message", message: message %>
    <% end %>
  </div>
</div>