config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  resources :projects do
    resources :add_project_member, only: %w[new create destroy]
    resources :missions, only: %w[show new create edit update destroy] do
      resources :tasks, only: %w[show new create edit update destroy]
      resources :topics, only: %w[show new create edit update destroy] do
        resources :messages
      end
    end
  end
  resources :users, only: %w[show update destroy]

end

app/views/shared/_back.html.erb
<% if params[:controller] == 'users' && params[:action] == 'show' %>
  <%= link_to '', projects_path(current_user), class: 'fas fa-backward bigger-icon' %>
<% elsif params[:controller] == 'pages' && params[:action] == 'home' %>

<% elsif params[:controller] == 'dashboard' && params[:action] == 'show' %>
  <%= link_to '', :back, class: 'fas fa-backward bigger-icon' %>
<% elsif params[:controller] == 'projects' && params[:action] == 'new' %>
  <%= link_to '', root_path, class: 'fas fa-backward bigger-icon' %>
<% elsif params[:controller] == 'projects' && params[:action] == 'show' %>
  <%= link_to '', root_path, class: 'fas fa-backward bigger-icon' %>
<% elsif params[:controller] == 'missions' && params[:action] == 'new' %>
  <%= link_to '', project_path(params[:project_id]), class: 'fas fa-backward bigger-icon' %>
<% elsif params[:controller] == 'add_project_member' && params[:action] == 'new' %>
  <%= link_to '', project_path(params[:project_id]), class: 'fas fa-backward bigger-icon' %>
<% elsif params[:controller] == 'projects' && params[:action] == 'edit' %>
  <%= link_to '', project_path(params[:id]) , class: 'fas fa-backward bigger-icon'  %>
<% elsif params[:controller] == 'missions' && params[:action] == 'show' %>
  <%= link_to '', project_path(params[:project_id]), class: 'fas fa-backward bigger-icon' %>
<% elsif params[:controller] == 'tasks' && params[:action] == 'new' %>
  <%= link_to '', project_mission_path(params[:project_id],params[:mission_id]), class: 'fas fa-backward bigger-icon' %>
<% elsif params[:controller] == 'topics' && params[:action] == 'new' %>
  <%= link_to '', project_mission_path(params[:project_id],params[:mission_id]), class: 'fas fa-backward bigger-icon' %>
<% elsif params[:controller] == 'missions' && params[:action] == 'edit' %>
  <%= link_to '', project_mission_path(params[:project_id],params[:id]), class: 'fas fa-backward bigger-icon' %>
<% elsif params[:controller] == 'topics' && params[:action] == 'show' %>
  <%= link_to '', project_mission_path(params[:project_id],params[:mission_id]), class: 'fas fa-backward bigger-icon' %>
<% elsif params[:controller] == 'topics' && params[:action] == 'edit' %>
  <%= link_to '', project_mission_topic_path(params[:project_id],params[:mission_id], params[:id]), class: 'fas fa-backward bigger-icon' %>
<% elsif params[:controller] == 'tasks' && params[:action] == 'show' %>
  <%= link_to '', project_mission_path(params[:project_id],params[:mission_id]), class: 'fas fa-backward bigger-icon' %>
<% elsif params[:controller] == 'tasks' && params[:action] == 'edit' %>
  <%= link_to '', project_mission_task_path(params[:project_id],params[:mission_id], params[:id]), class: 'fas fa-backward bigger-icon' %>
<% else %>
  <%= link_to '', :back, class: 'fas fa-backward bigger-icon' %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar sticky-top d-flex justify-content-around">
  <% if user_signed_in? %>
    <div class="navbar-item nav-link">
      <%= render 'shared/back' %>
    </div>
    <% if params[:controller] == 'pages' && params[:action] == 'home' %>
      <div class="navbar-item">
        <%= link_to "Home", projects_path(current_user) %>
      </div>
    <% end  %>
    <div class="navbar-item">
      <%= link_to "L!", projects_path, class: "logo bigger-icon red glow-red" %>
    </div>
    <div class="navbar-item">
      <%= link_to "My account", user_path(current_user) %>
      <% if current_user.name == nil or current_user.name == "" %>
        <div class="add_username">No username</div>
      <% end %>
    </div>
    <div class="navbar-item">
      <%= link_to "Log out", destroy_user_session_path, method: :delete %>
    </div>
  <% else %>
    <div class="navbar-item d-flex justify-content-start">
      <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
      <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
  </div>
    <div class="navbar-item">
    <%= link_to "L!", projects_path, class: "logo bigger-icon red glow-red" %>
    </div>
  <% end %>
</div>