config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  resources :projects do
    resources :add_project_member, only: %w[new create destroy]
    resources :missions, only: %w[show new create edit update destroy] do
      resources :tasks, only: %w[show new create edit update destroy]
      resources :topics, only: %w[show new create edit update destroy] do
        resources :messages
      end
    end
  end
  resources :users, only: %w[show update destroy]

end

app/models/project.rb
class Project < ApplicationRecord
  has_many :missions, dependent: :destroy
  has_many :project_members, dependent: :destroy
  has_many :users, through: :project_members
  belongs_to :manager, class_name: "User", foreign_key: "user_id"
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :is_member?, only: [:show]
    before_action :is_manager?, only: [:edit, :update, :destroy]

  def index
    @projects = current_user.projects
  end

  def show
    @project = Project.find(params[:id])
    @missions = Project.find(params[:id]).missions
    @status = "#{@project.status.to_s}%"
  end

  def new
    @project = Project.new
  end

  def edit
    @project = Project.find(params[:id])
  end


  def create
    project = Project.new(project_params)
    project.status = 0
    project.manager = current_user
    project.save
    ProjectMember.create(user: current_user, project: project)

    redirect_to project_path(project)
  end

  def update
    project = Project.find(params[:id])
    project.update(project_params)

    redirect_to project_path(project)
  end

  def destroy
    project = Project.find(params[:id])
    project.destroy

    redirect_to projects_path
  end

  private

  def is_member?
      redirect_to root_path if current_user.projects.find_by(id: params[:id]).nil?
  end

  def is_manager?
    if Project.find_by(id: params[:id]) != nil && Project.find_by(id: params[:id]).manager == current_user
    else
      redirect_to root_path
    end
  end

  def project_params
    params.require(:project).permit(:title, :description, :delivery_date)
  end

end

app/views/projects/edit.html.erb
<br>
<div class="container">
  <div class="form">
    <%= simple_form_for @project, url: project_path(@project), method: :patch do |f| %>
    <h2 class="far fa-edit"> Update your Objective</h2>
    <%= f.input :title, label: "Title:" %>
    <%= f.input :description, label: "Description:", :input_html => { :rows => 7 , :style => 'width: 100%'} %>
    <%= f.input :delivery_date, label: "Delivery:" %>

    <%= f.button :submit, value: 'Update', "data-disable-with" => "Creating..", class:"btn btn-outline-primary" %>
  <% end %>
  </div>

  <br>
</div>

app/views/projects/index.html.erb
<div class="container">
  <div class="card text-center">
    <div class="card-header">
      <ul class="nav nav-pills card-header-pills">
        <li class="nav-item">
            <%= link_to " Defining a new objective", new_project_path, class: 'nav-link fas fa-hands-helping bigger-icon'%>
        </li>
      </ul>
    </div>
  </div>
  <br>
  <% @projects.each do |project|  %>
    <div class="projects-cards">
      <%= link_to project_path(project) do %>
        <div class="justify-content-center">
          <div class="project-card">
            <div class="project-card-title">
              <h1 class="text-center">
                <span class="fas fa-hands-helping middle-icon"></span>
                <%= project.title %>
              </h1>
              <div class="ldBar label-center" data-value="<%= project.status %>" data-preset="stripe"> </div>
              <br>
          </div>
        </div>
      <% end %>
    </div>
    <br>
    <% end %>
  </div>

app/views/projects/new.html.erb
<br>
<div class="container">
  <div class="form">
    <%= simple_form_for @project, url: projects_path, method: :post do |f| %>
    <h2 class="fas fa-hands-helping">+ Define a new Objective</h2>
    <%= f.input :title, label: "Title:" %>
    <%= f.input :description, label: "Description:", :input_html => { :rows => 7 , :style => 'width: 100%'} %>
    <%= f.input :delivery_date, label: "Delivery:" %>

    <%= f.button :submit, value: 'Start', "data-disable-with" => "Creating..", class:"btn btn-outline-primary" %>
  <% end %>
  </div>

  <br>
</div>

app/views/projects/show.html.erb
<br>
<div class="container">
  <div class="card text-center">
    <div class="card-body">
      <br>
      <h2 class="card-title fas fa-hands-helping"> <%= @project.title %></h4>
    <div class="progress">
      <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: <%= @status %>"><%= @status %></div>
    </div>
      <ul class="nav nav-pills card-header-pills">
        <li class="nav-item">
          <%= link_to "+", new_project_mission_path(@project), class: 'nav-link fas fa-tasks bigger-icon' %>
          <div class="hint">New action plan</i> </div>
        </li>
        <% if current_user == @project.manager %>
          <li class="nav-item">
            <%= link_to "+", new_project_add_project_member_path(@project), class: 'nav-link fas fa-user bigger-icon' %>
            <div class="hint">New team member</i></div>
          </li>
        <% end %>
        <% if current_user == @project.manager %>
          <li class="nav-item">
            <%= link_to "", edit_project_path(@project), method: :get, class: 'nav-link far fa-edit bigger-icon' %>
            <div class="hint">Edit objective</i></div>

          </li>
        <% end %>
        <% if current_user == @project.manager %>
          <li class="nav-item">
            <%= link_to "", @project, method: :delete, data: { confirm: 'WARNING you will delete an entire objective!', disable_with: 'loading...' }, class: 'nav-link far fa-trash-alt bigger-icon' %>
          <div class="hint red">Delete objective</i></div>
          </li>

        <% end %>

      </ul>
      <p class="card-text"><%= simple_format(@project.description) %></p>
      <br><hr><br>
      <h2 class="card-title fas fa-users"> Members: </h4>
      <p class="card-text">
        <% @project.users.each do |user| %>
          <% if user.name != nil && user.name != "" %>
            <%= user.name %>
          <% else %>
            <%= user.email %>
          <% end %>
          <% if user != current_user && current_user == @project.manager %>
            <%= link_to "-", project_add_project_member_path(@project, user),
                            method: :delete, data: { confirm: 'WARNING you will remove this member from this project!',
                            disable_with: 'loading...' }, class: 'nav-link fas fa-user middle-icon' %>
          <% end %>
          <br>
        <% end %>
      </p>
      <br><hr><br>
      <h2 class="card-title fas fa-calendar-alt"> Delivery: </h4>
      <p class="card-text"><%= @project.delivery_date.strftime("%d/%m/%Y") %></p>
      <br>
    </div>
  </div>
  <br>
  <% if @missions.count == 0 %>
    <%= link_to new_project_mission_path(@project) do %>
      <div class="card-product">
        <div class="card-product-infos">
          <h2>
            Add your first action plan <i class="far fa-plus-square middle-icon"></i>
          </h2>
        </div>
      </div>
    <% end %>
  <% else %>
    <% @missions.order(priority: :asc, due_date: :asc, status: :asc).each do |mission|  %>
      <%= link_to project_mission_path(mission.project, mission) do %>
        <div class="card-product">
          <div class="card-product-infos">
            <h2><span class="fas fa-tasks <%= status_color(mission) %>"></span> <%= mission.title %></h2>
            <p><span class="far fa-calendar-alt"> <strong><%= mission.start_date.strftime("%d/%m/%Y") %></strong> to <strong><%= mission.due_date.strftime("%d/%m/%Y") %> </strong></span></p>
            <div class="d-flex justify-content-between">
            <p>
              <span class="fas fa-star <%= priority_color(mission) %>"></span> <%= mission.priority %>
            </p>
            <p>
              <span class="fas fa-spinner <%= status_color(mission) %>"><%= "#{mission.status.to_s}%"%></span>
            <p>
            </div>
            <% mission.tasks.each do |task|  %>
              |<span class="fas fa-thumbtack <%= status_color(task) %> "></span>
              <% end  %>
          </div>
        </div>
      <% end %>
    <br>
    <% end %>
<% end %>
</div>