config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  resources :projects do
    resources :add_project_member, only: %w[new create destroy]
    resources :missions, only: %w[show new create edit update destroy] do
      resources :tasks, only: %w[show new create edit update destroy]
      resources :topics, only: %w[show new create edit update destroy] do
        resources :messages
      end
    end
  end
  resources :users, only: %w[show update destroy]

end

app/models/mission.rb
class Mission < ApplicationRecord
  belongs_to :project
  has_many :topics, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :mission_members, dependent: :destroy
  has_many :users, through: :mission_members
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  before_action :is_member?, only: [:show, :new, :create]
  before_action :is_manager?, only: [:edit, :update, :destroy]

  def show
    @mission = Mission.find(params[:id])
    @tasks = @mission.tasks

    @usernames = []
    @mission.users.each do |user|
      if user.name != nil && user.name != ""
        @usernames << user.name
      else
        @usernames << user.email
      end
    end
    @status = "#{@mission.status.to_s}%"
  end

  def new
    @mission = Mission.new
    @project = Project.find(params[:project_id])
  end

  def create
    mission = Mission.new(mission_params)
    mission.project = Project.find(params[:project_id])
    mission.status = 0
    mission.save
    MissionMember.create(mission: mission, user: current_user)
    mission.project.users.each do |user|
      if mission.users.include?(user)
      else
        MissionMember.create(mission: mission, user: user)
      end
    end

    redirect_to project_path(mission.project)
  end

  def edit
    @mission = Mission.find(params[:id])
  end

  def update
    mission = Mission.find(params[:id])
    mission.update(mission_params)
    mission.save
    redirect_to project_mission_path(mission)
  end

  def destroy
    mission = Mission.find(params[:id])
    project = mission.project
    mission.destroy

    redirect_to project_path(project)
  end

  private

  def mission_params
    params.require(:mission).permit(:title, :description, :start_date, :due_date, :priority, :project_id)
  end

  def is_member?
    if Project.find_by(id: params[:project_id]) != nil && Project.find_by(id: params[:project_id]).users.include?(current_user)
    else
      redirect_to root_path
    end
  end

  def is_manager?
    if Mission.find_by(id: params[:id]) != nil && Mission.find_by(id: params[:id]).project.manager == current_user
    else
      redirect_to root_path
    end
  end
end

app/views/missions/edit.html.erb
<br>
<div class="container">
  <div class="form">
    <%= simple_form_for @mission, url: project_mission_path(@mission), method: :patch do |f| %>
    <h2 class="far fa-edit"> Update your action plan</h2>
    <%= f.input :title, label: "Title:" %>
    <%= f.input :description, label: "Description:", :input_html => { :rows => 7 , :style => 'width: 100%'} %>
    <%= f.input :start_date, label: "Start:" %>
    <%= f.input :due_date, label: "Due date:" %>
    <%= f.input :priority, label: 'Priority', collection: ['Critical', 'Moderate', 'Negligible'], required: true %>

    <%= f.button :submit, value: 'Update', "data-disable-with" => "Creating..", class: "btn btn-outline-primary" %>
  <% end %>
  </div>

  <br>
</div>

app/views/missions/new.html.erb
<br>
<div class="container">
  <div class="form">
    <%= simple_form_for @mission, url: project_missions_path(@project), method: :post do |f| %>
      <h2 class="fas fa-tasks">+ New action plan</h2>
      <%= f.input :title, label: "Title:" %>
      <%= f.input :description, label: "Informations:", :input_html => { :rows => 7 , :style => 'width: 100%'} %>
      <%= f.input :start_date, label: 'Start-date', :order => [:day, :month, :year] %>
      <%= f.input :due_date, label: 'End-date ', :order => [:day, :month, :year] %>
      <%= f.input :priority, label: 'Priority', collection: ['Negligible', 'Moderate', 'Critical'] %>
      <%= f.button :submit, value: 'Create', "data-disable-with" => "Creating..", class: "btn btn-outline-primary" %>
    <% end %>
  </div>

</div>

app/views/missions/show.html.erb
<br>
<div class="container">
  <div class="card text-center">
    <div class="card-body">
      <br>
      <h2 class="card-title fas fa-tasks"> <%= @mission.title %></h4>
      <p class="card-text"><%= simple_format(@mission.description) %></p>
    <div class="progress">
      <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: <%= @status %>"><%= @status %></div>
    </div>
      <ul class="nav nav-pills card-header-pills"><i class=""></i>
        <li class="nav-item">
          <%= link_to "+", new_project_mission_task_path(@mission.project, @mission), class: 'nav-link fas fa-thumbtack bigger-icon'  %>
                    <div class="hint">New task</i> </div>
        </li>
        <li class="nav-item">
          <%= link_to "+", new_project_mission_topic_path(@mission.project, @mission), class: 'nav-link far fa-comments bigger-icon'  %>
          <div class="hint">New topic</i> </div>

        </li>
        <% if current_user == @mission.project.manager%>
          <li class="nav-item">
            <%= link_to "", edit_project_mission_path(@mission.project, @mission), method: :get, class: 'nav-link far fa-edit bigger-icon' %>
            <div class="hint">Edit action plan</i> </div>

          </li>
          <li class="nav-item">
            <%= link_to "", "#", method: :delete, data: { confirm: 'Are you sure?', disable_with: 'loading...' }, class: 'nav-link far fa-trash-alt bigger-icon' %>
            <div class="hint red">Delete objective</i></div>
          </li>
        <% end %>
      </ul>
      <h4 class="card-title fas fa-star"> Priority: </h4>
      <p class="card-text"><%= @mission.priority %></p>
      <br><hr><br>
      <h2 class="card-title fas fa-calendar-alt"> Time: </h4>
      <p class="card-text">From <strong><%= @mission.start_date.strftime("%d/%m/%Y") %></strong> to <strong><%= @mission.due_date.strftime("%d/%m/%Y") %> </strong></p>
    </div>
    <br>
  </div>
    <br>
    <% if @mission.topics.count == 0 %>
      <%= link_to new_project_mission_topic_path(@mission.project, @mission) do %>
        <div class="card-product">
          <div class="card-product-infos">
            <h2>
              <i class="far fa-comments bigger-icon high"> Add your first topic</i>
            </h2>
          </div>
        </div>
        <br>
      <% end %>
    <% else %>
      <% @mission.topics.each do |topic| %>
        <%= link_to project_mission_topic_path(topic.mission.project, topic.mission, topic) do %>
          <div class="card-product">
            <div class="card-product-infos">
              <h2><span class="far fa-comments"></span> <%= topic.title %> </h2>
              <% if topic.messages.count > 0 && (topic.status == 2 || topic.status == nil) %>
                <p><%= "#{topic.messages.last.user.name} | #{topic.messages.last.updated_at}"  %></p>
                <p><%= topic.messages.last.content.truncate(460)%></p>
              <% elsif topic.messages.count == 0  %>
                <p>Collaboration is the key. Engage the conversation and let the magic happen !</p>
              <% else %>
                <i class="fas fa-lock"> Locked</i>
              <% end %>
            </div>
        </div>
        <% end %>
        <br>
      <% end %>
    <% end %>
    <% if @mission.tasks.count == 0 %>
      <%= link_to new_project_mission_task_path(params[:project_id], params[:id]) do %>
        <div class="card-product">
          <div class="card-product-infos">
            <h2>
              <i class="fas fa-tasks bigger-icon high"> Add your first task</i>
            </h2>
          </div>
        </div>
      <% end %>
    <% else %>
    <% @mission.tasks.order(priority: :asc, due_date: :asc, status: :asc).each do |task| %>
    <%= link_to project_mission_task_path(params[:project_id], @mission, task) do %>
      <div class="card-product no-link-style">
        <div class="card-product-infos">
          <h2><span class="fas fa-thumbtack <%= status_color(task) %>"></span> <%= task.title %></h2>
          <p class="far fa-calendar-alt"> <strong> <%= task.start_date.strftime("%d/%m/%Y") %></strong> to <strong><%= task.due_date.strftime("%d/%m/%Y") %></strong> </p>
          <p><span class="fas fa-star <%= priority_color(task) %>"> <%= task.priority %> </span></p>
          <p class="card-title">
            <span class="fas fa-spinner <%= status_color(task) %>"><%= "#{task.status.to_s}%" %></span>
          </p>
        </div>
      </div>
    <% end %>
    <br>
    <% end %>
  <% end %>
</div>